[package]
name = "check-tls-certs"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.0.0-beta.4"
once_cell = "1.8.0"
rustls = { version = "0.19", features = ["dangerous_configuration"] }
rustls-native-certs = "0.5.0"
webpki = "0.21"
webpki-roots = "0.21"
